title: ZDDHUB
slogan: Just for fun
author: zdd
email: zddhub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ZDDHUB's blog | Just for fun

baseurl: ""
url: http://zddhub.github.io

twitter_username: zddhub
github_username:  zddhub

gravid:
  date_format: "%m/%d/%Y"

language: zh-CN
enable_reward: true

# Build settings
markdown: kramdown
# theme: gravid # If one day github support customize gem theme, will open this line
exclude:
  - Gemfile
  - Gemfile.lock
